### ISSUE TITLE
Manual prevalence entry v1 proposal

### ISSUE THREAD

**Issue by octern** [microCOVID/microCOVID#1826]
### **Goal of this proposal**
- Make the site sustainably usable for users who are willing to look up and manually input **one** piece of data about local COVID rates. 
Note: this is based on several discussions, primarily on #disc-code and [these meetings](https://docs.google.com/document/d/1Wf4CVQh6ImoaapoqYeQU_3Yw2CJFbPVUpDqn5AIhEd8/edit#)

### **Proposed changes:**

* Blue infobox
   - [x] Move the specific data entry instructions from the blue infobox into a box immediately under the "step 1" header (#1821, #1827)
* Reported cases field:
	- [ ] Label as "weekly new cases / 100k population". 
	- [x] remember past values, the same way we do now
	- [x] No default value; if there's not a past value leave it blank so the user has to enter something
* Population field:
	- [x] If the box would be blank, set it to 100,000 (#1830)
	- [x] Remember past values, the same way we do now (If the past value isn't 100k, the user will probably also have a saved value for total cases, not per 100k)
	- [ ] If the value is not 100,000 show text with a warning
* Change-over-past-week field
	- [x] We do not expect users to be able to obtain this value with a reasonable amount of effort. 
	- [ ] #1834
	- [ ] **for the present version** at least, hide the field (visually only, so that the adjusted prevalence formula still has access to the parameter it expects)
* Test positivity rate field
	- [x] Users could look this up but it may be an unreasonable amount of work compared to the improvement in accuracy. 
	- [x] **for the present version** wipe any saved values in this field and set to 10% (a cautious, ie high, estimate) (#1830)
	- [ ] **for the present version**, at least, hide the field (visually only, so the ) adjusted prevalence formula still has access to the parameter it expects)
* Vaccine rate field
	- [x] This currently has trivial effects on adjusted prevalence
	- [x] Carry forward past values, or by default set to zero -- it doesn't matter as long as there's some value in it
	- [ ] Hide the field (visually only, so that the adjusted prevalence formula still has access to the parameter it expects)

### Technical issues to deal with:
* Under some circumstances past values can override the values we try to set as defaults (see #1823 )
* ...?

### Process
The current agreement was to develop this on its own branch ([manual-entry-v1](https://github.com/microCOVID/microCOVID/tree/manual-entry-v1)), relying on the Netlify builds for testing (pending resolution of #1828). Once we have all the changes in place, there may or may not be interest in releasing behind a feature flag. 

### Changes we could make in a followup update:
* Hide the population box but offer a checkbox option to expose it, and change the field labels, if the user does want to enter total cases and actual population
* Remove the warning in the middle of the calculator about not having vaccination rates (https://github.com/microCOVID/microCOVID/issues/1817).
* Agree on language to use for referring to prevalence and data input

**Comment by jaraco** [comment]
@justinhaaheim, I've a couple of proposals linked above to take care of some of the easy tasks in this list. I'm hoping you have time to take on some of the slightly more involved changes.

**Comment by octern** [comment]
> I think it only makes sense to stipulate "weekly per 100000" if we're eliminating the total population field.

You're correct, but I also really want to make it as easy as possible for people to go through the unavoidably convoluted steps we're asking them to go through, and doing the mental contortions of "I'm pretending the population is 100,000" will be hard for some nonexperts. In an ideal world I'd say we should use the per 100,000 label and hide "total population" box, but also offer a checkbox that reveals it and simultaneously changes the label on the prevalence box to remove the "per 100,000" part. But that is some extra work. 

What if the "total population" box had text below it that said "if using cases per 100,000, leave this at 100,000"?

**Comment by jaraco** [comment]
> What if the "total population" box had text below it that said "if using cases per 100,000, leave this at 100,000"?

That's not too bad. Perhaps additionally or alternately change the label to "case population" or similar so "total" doesn't mislead.

I believe the long term plan is to provide a simpler interface (Kelly Ann's design), relieving much of the expertise needed.

In light of those concerns, let me know where you land and we'll implement that (or update the plan above).

**Comment by justinhaaheim** [comment]
> @justinhaaheim, I've a couple of proposals linked above to take care of some of the easy tasks in this list. I'm hoping you have time to take on some of the slightly more involved changes.

@jaraco Which ones are you thinking will be more involved? Happy to take on whatever.

**Comment by justinhaaheim** [comment]
@octern et al, re: #1834 I'm wondering if the right approach here would be to wipe *all* saved values for all fields. That would be technically simpler and cleaner.

If we're wiping an individual field we'll need to clarify:
- Does this mean we're wiping *only* the values saved into the browser's local storage, but continuing to honor any values that may be present in URL parameters from saved links? Or should the values in saved links be invalidated too?
- Once this value is wiped/invalidated, should future values be saved/honored?

**Comment by jaraco** [comment]
> @jaraco Which ones are you thinking will be more involved? Happy to take on whatever.

@justinhaaheim Honestly, any of the unchecked items is fine. It looks like you've grabbed one, but feel free to grab any or all of the others. There's some uncertainty about the Reported Cases field label, so maybe follow your instinct based on what's been discussed.

**Comment by jaraco** [comment]
> I'm wondering if the right approach here would be to wipe _all_ saved values for all fields.

I'm slightly opposed to this approach because it's helpful to me personally to be able to see where things were last time I used it... as a reminder of how things are different from last time. But maybe it makes sense to simplify, especially since we're talking about hiding most of the fields... the only inputs are going to be the weekly cases and maybe a population override.

**Comment by octern** [comment]
> If we're wiping an individual field we'll need to clarify:
> 
>     * Does this mean we're wiping _only_ the values saved into the browser's local storage, but continuing to honor any values that may be present in URL parameters from saved links? Or should the values in saved links be invalidated too?

My ideal would be "next time the user visits, give them a clean site as if they were visiting for the first time, and from then on save values the same way we do now." But I don't see an efficient way to do that without changing the names of the fields, which would probably cause other problems. 

>     * Once this value is wiped/invalidated, should future values be saved/honored?

Reported cases and population should save values the way they do now. The other three boxes should be hidden and always use their defaults from now on.

**Comment by jaraco** [comment]
After #1837, I'm declaring this effort complete.
